FROM nginx:stable-alpine3.17
COPY src /usr/share/nginx/html

# Comando para levantar un contenedor anónimo
# docker build . 

# Comando para levantar un contenedor con nombre "UnNombre"
# docker build -t UnNombre . 

# Comando para ejecutar un contenedor que está parado
# docker run [identificador] o [nombre si no es anónimo]


